  $ python3 find_mismatches.py
  Traceback (most recent call last):
    File "$TESTCASE_ROOT/find_mismatches.py", line 13, in <module>
      print(find_mismatches(dict1, dict2))
    File "$TESTCASE_ROOT/find_mismatches.py", line 4, in find_mismatches
      if data != d2[key]:
  KeyError: 'model'
  [1]
